#Day 1


Q1. What's the difference between a list and a tuple?

Lists are mutable, meaning their elements can be changed after creation. They are defined using square brackets [].

Tuples are immutable, meaning their elements cannot be changed after creation. They are defined using parentheses ().

Q2. Write a function that returns the square of a number.



In [14]:

def square(number):
    return number * number

Q3. What does *args do in a function signature?

The *args parameter allows a function to accept any number of positional arguments.

Inside the function, args becomes a tuple containing all the passed arguments:

Q4. What’s the output of a basic for loop over range(5)?


In [15]:
for i in range(5):
    print(i)

# Output:
# 0
# 1
# 2
# 3
# 4

0
1
2
3
4


Q5.What is a dictionary comprehension?

A dictionary comprehension is a concise way to create dictionaries. It follows a similar syntax to list comprehensions but uses curly braces {} and specifies both a key and a value.



In [16]:
#Example:
squares = {x: x**2 for x in range(5)}
print(squares)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}


#Day 2


Q1. What is broadcasting in NumPy?


Broadcasting lets NumPy perform operations between arrays of different shapes without you manually looping or resizing them. NumPy automatically "stretches" the smaller array across the larger one, as long as their shapes are compatible.

Q2. How do you select all rows where a column value > 10 in a 2D array?

In [17]:
import numpy as np

arr = np.array([[5,  12, 3],
                [11, 2,  8],
                [4,  15, 9],
                [8,  7,  6]])

result = arr[arr[:, 1] > 10]
print(result)

[[ 5 12  3]
 [ 4 15  9]]


Q3. Difference between .reshape() and .flatten()?

Reshape  changes the array's dimensions (e.g. 1D → 2D) without changing the data.

Flatten always collapses to 1D, and returns a copy (safe to edit without affecting the original).

Q4. What does axis=0 vs axis=1 mean in np.sum()?


axis=0 : sum down each column (collapses rows, one result per column).

axis=1 : sum across each row (collapses columns, one result per row).

Q5. How do you generate a random array of shape (5,5)?


In [18]:
np.random.rand(5, 5)
np.random.normal(size=(5,5))

array([[-0.55817445, -1.53242437, -0.94415808,  0.69770752, -0.72254229],
       [-0.63379453, -0.3930688 , -0.97675333, -1.10080125, -0.11483852],
       [ 0.11506077, -1.024772  ,  0.80482356,  0.8317681 ,  0.30322927],
       [ 1.18259294,  1.94333713,  1.02259691, -0.28783523, -1.08889832],
       [ 0.57753551,  2.12721481, -1.34604779,  0.48779347,  1.46277491]])